language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
# Setup anaconda
before_install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

cache:
  directories:
    - $HOME/.cache/pip

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy astropy
  - source activate test-environment
  - pip install pyastronomy
  - touch /home/travis/.pyaConfigWhere && echo "/home/travis/build/jason-neal/PyA_data" >> /home/travis/.pyaConfigWhere
  - mkdir /home/travis/build/jason-neal/PyA_data

  - python setup.py install

  - pip install pytest-cov python-coveralls codeclimate-test-reporter codacy-coverage
  - pip install -r requirements.txt

script:
  - pytest --cov=baraffe_tables/ --cov-report term-missing --durations 5
  - coverage xml

after_success:
  - coveralls
  - codeclimate-test-reporter
  - python-codacy-coverage -r coverage.xml
